---
title: "week 7"
author: "Amit Balia"
date: "7/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Installing package tidyverse
install.packages("tidyverse")
library(tidyverse)
```


```{r setup, include=TRUE}
#mpg contains data of cars and its models
mpg
```


```{r setup, include=TRUE}
#ggplot
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```


```{r setup, include=TRUE}
#get class of each car
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
```


```{r setup, include=TRUE}
#Sample gragh 1
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))

#sample graph 2
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, shape = class))
```

```{r setup, include=TRUE}
#Change point color to blue:
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
``` 
```{r setup, include=TRUE}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)
```
```{r setup, include=TRUE}
#facet_grid() is used to facet plot on combination of two variables
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)
```

```{r setup, include=TRUE}
ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy))

#display
ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy))
```
```{r setup, include=TRUE}
# set line type
ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))
```
```{r setup, include=TRUE}
#displ1
ggplot(data = mpg) +geom_smooth(mapping = aes(x = displ, y = hwy))
#displ2              
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
#displ3
ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, color = drv),
    show.legend = FALSE
  )
```

```{r setup, include=TRUE}
#Multiple geom functions can be added to display to display multiple geoms in same plot
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
```

```{r setup, include=TRUE}
#pass mapping sets
#same plot generated as above
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point() + geom_smooth()
```

```{r setup, include=TRUE}
#To specify different data for each layer
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)
```

```{r setup, include=TRUE}
#basic bar chart with geom_bar()
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut))
```

```{r setup, include=TRUE}
#stat_count an be used instead of geom_bar(). Same bar graph is generated
ggplot(data = diamonds) + 
  stat_count(mapping = aes(x = cut))
```

```{r setup, include=TRUE}
demo <- tribble(
  ~cut,         ~freq,
  "Fair",       1610,
  "Good",       4906,
  "Very Good",  12082,
  "Premium",    13791,
  "Ideal",      21551
)

ggplot(data = demo) +
  geom_bar(mapping = aes(x = cut, y = freq), stat = "identity")
```
```{r setup, include=TRUE}
#bar chart of proportion, rather than count
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))
```


```{r setup, include=TRUE}
#summarise the y values for each unique x value
ggplot(data = diamonds) + 
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )
```

```{r setup, include=TRUE}
#bar chart can be coloured using colour or fill
#displ1
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, colour = cut))
#displ2
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = cut))
```


```{r setup, include=TRUE}
ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + 
  geom_bar(alpha = 1/5, position = "identity")
#display
ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + 
  geom_bar(fill = NA, position = "identity")
```

```{r setup, include=TRUE}
#position = "fill" works like stacking, but makes each set of stacked bars the same height. 
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")
```

```{r setup, include=TRUE}
#place overlaping objects next to each other
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")
```


```{r setup, include=TRUE}
#use of polar co ordinates
bar <- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = cut), 
    show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

#display
bar + coord_flip()
#display 2
bar + coord_polar()
```
